#!/usr/bin/env bash
set -eo pipefail
scriptDir=$(dirname $0)

libs=$scriptDir/ducttape.jar
libs=$libs:$scriptDir/lib/scala-library-2.9.2.jar
libs=$libs:$scriptDir/lib/scala-optparse-1.1.jar
libs=$libs:$scriptDir/lib/commons-lang3-3.1.jar
libs=$libs:$scriptDir/lib/commons-io-2.2.jar

#     -XX:MaxJavaStackTraceDepth=25 \
java -Xmx1g \
     -cp $libs \
     Ducttape "$@"
