#!/usr/bin/env bash
set -euo pipefail
set -x

repo=/home/jhclark/software/cdec
cores=16

mode=$1
dest=$2

$(dirname $0)/gimme_repo_git $mode $repo $dest

case $mode in
    gimme)
        cd $dest
        echo >&2 "Building cdec using scons"
	scons -j $cores --with-boost=$HOME/prefix
	;;
    *) ;;
esac
