#!/usr/bin/env bash
set -euo pipefail

mode=$1
dest=$2

repo=/home/jhclark/software/multeval

$(dirname $0)/gimme_repo_git $mode $repo $dest

case $mode in
    gimme)
	cd $dest
	./get_deps.sh
	ant
	;;
    *) ;;
esac
