#!/usr/bin/env bash
set -euo pipefail

repo=/home/jhclark/software/srilm
cores=16

$(dirname $0)/gimme_repo_symlink $@

case $1 in
    repo-version) ;;
    dest-version) ;;
    gimme)
        dest=$3
        cd $dest
        make -j $cores SRILM=$PWD MACHINE_TYPE=i686-m64 MAKE_PIC=yes World

	# Overwrite version
	cp ~/workspace/srilm/RELEASE $dest/gimme.ver
        ;;
    *) ;;
esac
