#!/usr/bin/env bash
set -eo pipefail
scriptDir=$(dirname $0)

# Just use the sbt JAR from our parent directory
java -Dfile.encoding=UTF8 \
     -Xmx512M \
     -Xss1M \
     -XX:+CMSClassUnloadingEnabled \
     -XX:MaxPermSize=256m \
     -jar $scriptDir/../lib/sbt-launch.jar \
     "$@"
